language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script: |
  rustup component add rustfmt-preview &&
  rustup component add clippy-preview
script: |
  cargo fmt -- --check &&
  cargo clippy -- -D clippy::all &&
  cargo build --verbose &&
  cargo test  --verbose -- --test-threads 1
cache: cargo
